name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker compose build

      - name: Push Docker image to Docker Hub
        run: |
          docker tag web:latest ${{ secrets.DOCKER_USERNAME }}/web:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/web:latest

      - name: Start Docker container
        run: |
          docker compose up -d

      - name: Test container
        run: |
          sleep 10 
          curl -f http://localhost || exit 1

      - name: Stop
        run: |
          docker compose down
