name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker compose build

      - name: Test Docker image
        run: |
          docker compose up -d
          sleep 10 
          curl -f http://localhost || exit 1
          docker compose down
